# Generated by Django 5.2.8 on 2025-11-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('pwm_duty_cycle', models.FloatField()),
                ('pwm_frequency', models.FloatField()),
                ('pwm_period', models.FloatField()),
                ('percentage_param', models.FloatField()),
            ],
            options={
                'verbose_name': 'Sensor Data Entry',
                'verbose_name_plural': 'Sensor Data Entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
